version: '3.8'
services:
  connective-chat:
    build:
      context: .
      target: dev
    volumes:
      - ./src:/src
    command: npm run start:dev
    ports:
      - "3001:3001"
    env_file:
      - .env
      