version: '3.8'
services:
  connective-socket:
    container_name: connective-socket
    build:
      context: .
      target: dev
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - .env
      