version: '3.8'
services:
  connective-socket:
    container_name: connective-socket
    build:
      context: .
      target: production
    command: pm2 start ./build/server.js --no-daemon
    env_file:
      - .env
  nginx:
    container_name: connective-web-server
    build: ./nginx
    ports:
      - 80:80
