version: '3.8'
services:
  connective-chat:
    build:
      context: .
      target: production
    volumes:
      - ./src:/src
    command: npm run start
    ports:
      - "3000:3000"
    env_file:
      - .env
