version: '3.8'
services:
  connective-socket:
    container_name: connective-socket
    build:
      context: .
      target: production
    command: pm2 start ./build/server.js --no-daemon
    env_file:
      - .env
  nginx:
    container_name: connective-web-server
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: connective-certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
