exports.categoryOptions = [
    {value: "all", label: "All"},
    {value: '1', label: 'Arts and Culture'},
    {value: '2', label: 'Blockchain and Crypto Currency'},
    {value: '3', label: 'Community Mobilization'},
    {value: '4', label: 'Creative Production'},
    {value: '5', label: 'Education'},
    {value: '6', label: 'Entrepreneurship'},
    {value: '7', label: 'Fashion and Style'},
    {value: '8', label: 'Food and Drink'},
    {value: '9', label: 'Government and Politics'},
    {value: '10', label: 'Health and Self-Improvement'},
    {value: '11', label: 'Journalism and Publishing'},
    {value: '12', label: 'Local Interest'},
    {value: '13', label: 'Marketing and Sales'},
    {value: '14', label: 'Nonprofits and Volunteering'},
    {value: '15', label: 'Operations'},
    {value: '16', label: 'Product, Design, and UX'},
    {value: '17', label: 'Products and Consumer Reviews'},
    {value: '18', label: 'Professional'},
    {value: '19', label: 'Real Estate'},
    {value: '20', label: 'Science and Technology'},
    {value: '21', label: 'Sports and Games'},
    {value: '22', label: 'Travel and Outdoors'},
]